#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python ./backend/community_job_portal/manage.py migrate
python ./backend/community_job_portal/manage.py runserver_plus 0.0.0.0:8000
python ./backend/community_job_portal/manage.py collectstatic --no-input --clear
